---
- name: Windows update
  hosts: all
  tasks:
    - name: Get whoami information
      ansible.windows.win_whoami:
    - name: Search-only, return list of found updates (if any), log to C:\ansible_wu.txt
      ansible.windows.win_updates:
        category_names: 
        - CriticalUpdates
        - SecurityUpdates
        - UpdateRollups
        state: searched
        log_path: C:\ansible_wu.txt
    - name: Exclude updates based on the update title
      ansible.windows.win_updates:
        category_names:
        - SecurityUpdates
        - CriticalUpdates
        reject_list:
        - Windows Malicious Software Removal Tool for Windows
        - \d{4}-\d{2} Cumulative Update for Windows Server 2016

    - name: Install all critical and security updates
      ansible.windows.win_updates:
        category_names:
        - CriticalUpdates
        - SecurityUpdates
        - UpdateRollups
        state: installed
        reboot: yes
